# Step 1: Build the React app
FROM node:20-alpine AS builder
WORKDIR /app

# Accept build-time environment variables (build args)
ARG VITE_KC_URL
ARG VITE_KC_REALM
ARG VITE_KC_CLIENT_ID

ARG VITE_CHATBOT_URL
ARG VITE_GAME_REGISTRY_URL
ARG VITE_GAMEPLAY_URL
ARG VITE_PLAYER_URL
ARG VITE_STATISTICS_URL
ARG VITE_STOREFRONT_URL
ARG VITE_STRIPE_PUBLIC_KEY

# Set environment variables for the React build process
ENV VITE_KC_URL=$VITE_KC_URL
ENV VITE_KC_REALM=$VITE_KC_REALM
ENV VITE_KC_CLIENT_ID=$VITE_KC_CLIENT_ID
ENV VITE_STRIPE_PUBLIC_KEY=$VITE_STRIPE_PUBLIC_KEY

ENV VITE_CHATBOT_URL=$VITE_CHATBOT_URL
ENV VITE_GAME_REGISTRY_URL=$VITE_GAME_REGISTRY_URL
ENV VITE_GAMEPLAY_URL=$VITE_GAMEPLAY_URL
ENV VITE_PLAYER_URL=$VITE_PLAYER_URL
ENV VITE_STATISTICS_URL=$VITE_STATISTICS_URL
ENV VITE_STOREFRONT_URL=$VITE_STOREFRONT_URL

COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

# Step 2: Serve the React app with Node.js using `serve`
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
RUN npm install -g serve
EXPOSE 80
CMD ["serve", "-s", "dist", "-l", "80"]
